[package]
name = "captcha-rs"
version = "0.1.0"
edition = "2021"
authors = ["Samir Djelal <ssdjelal@gmail.com>"]
readme = "README.md"
repository = "https://github.com/samirdjelal/captcha-rs"
license = "MIT"
homepage ="https://github.com/samirdjelal/captcha-rs"
documentation = "https://github.com/samirdjelal/captcha-rs/blob/main/README.md"
keywords = ["captcha-rs", "captcha", "captcha rust", "rust"]
description = "Generate verification images dynamically"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
image = "0.23.14"
base64 = "0.13.0"
imageproc="0.22.0"
rusttype ="0.9.2"